export const brand = {
  name: "Stichting Lumina Collective",
  shortName: "Lumina Collective",
  domain: "stichtingluminacollective.nl",
  siteUrl: "https://stichtingluminacollective.nl",
  email: "info@stichtingluminacollective.nl",
  phone: "+31 6 17472738",
  phoneHref: "tel:+31617472738",
  claim: "Samen leven. Samen groeien.",
  description:
    "Stichting Lumina Collective in Tilburg verbindt vrouwen, nieuwkomers, jongeren en gezinnen. Samen werken we aan welzijn, ontwikkeling en gelijke kansen.",
  founded: 2026,
  kvk: "42082909",
  rsin: "869628409",
  establishmentNumber: "420829090000",
  sbi: "88992 - Sociaal-maatschappelijk welzijnswerk",
  address: {
    street: "Nimrodstraat 30",
    postalCode: "5042 WX",
    city: "Tilburg",
    country: "Nederland",
  },
  logoFull: "/brand/logo-mark.png",
  logoMark: "/brand/logo-mark.png",
  logoSocial: "/brand/logo-social.png",
  policyPlan: "/documenten/beleidsplan-lumina-2026-2030.pdf",
  iban: "NL41 INGB 0119 4296 59",
  ibanCompact: "NL41INGB0119429659",
} as const;
