import { defineField, defineType } from "sanity";

const required = "Bu alan zorunludur.";

export const pageSchema = defineType({
  name: "page",
  title: "Sayfa",
  type: "document",
  groups: [
    { name: "content", title: "İçerik", default: true },
    { name: "home", title: "Opbouw homepage" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Sayfa adı",
      type: "string",
      group: "content",
      description: "Yönetim panelinde görünecek iç isim.",
      validation: (Rule) => Rule.required().error(required),
    }),
    defineField({
      name: "slug",
      title: "URL adı",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 90 },
      description: "Sabit sayfalarda genelde hazır gelir. Gerekmedikçe değiştirmeyin.",
      validation: (Rule) => Rule.required().error(required),
    }),
    defineField({
      name: "pageKey",
      title: "Sabit sayfa",
      type: "string",
      group: "content",
      description: "Hangi sabit sayfayı düzenlediğinizi gösterir. Gerekmedikçe değiştirmeyin.",
      options: {
        list: [
          { title: "Ana sayfa", value: "home" },
          { title: "Hakkımızda", value: "over-ons" },
          { title: "Programlar", value: "programmas" },
          { title: "Ajanda", value: "agenda" },
          { title: "Katıl", value: "doe-mee" },
          { title: "İletişim", value: "contact" },
          { title: "Topluluk", value: "gemeenschap" },
          { title: "Haberler", value: "nieuws" },
        ],
      },
      validation: (Rule) => Rule.required().error(required),
    }),
    defineField({
      name: "heroTitle",
      title: "Sayfanın büyük başlığı",
      type: "string",
      group: "content",
      description: "Sayfanın en üstünde görünen ana başlık.",
      validation: (Rule) => Rule.required().error(required),
    }),
    defineField({
      name: "heroText",
      title: "Üst giriş metni",
      type: "text",
      rows: 3,
      group: "content",
      description: "Kısa, sıcak ve anlaşılır bir giriş yazın.",
      validation: (Rule) =>
        Rule.required().max(260).error("En fazla 260 karakter kullanın."),
    }),
    defineField({
      name: "heroImage",
      title: "Üst görsel",
      type: "image",
      group: "content",
      options: { hotspot: true },
      description: "Sıcak, gerçek ve sayfaya uygun bir fotoğraf kullanın.",
      fields: [
        defineField({
          name: "alt",
          title: "Alt metin",
          type: "string",
          description: "Fotoğrafta ne göründüğünü kısa şekilde açıklayın.",
          validation: (Rule) => Rule.required().error("Alt metin gereklidir."),
        }),
        defineField({
          name: "isPlaceholder",
          title: "Geçici görsel",
          type: "boolean",
          initialValue: false,
          description: "Bu fotoğraf daha sonra değiştirilecekse işaretleyin.",
        }),
      ],
    }),
    defineField({
      name: "body",
      title: "Ek metin blokları",
      type: "array",
      group: "content",
      of: [{ type: "block" }],
      description: "İsteğe bağlı. Daha uzun sayfa metinleri için kullanın.",
    }),
    defineField({
      name: "heroEyebrow",
      title: "Kleine tekst boven de titel",
      type: "string",
      group: "home",
      hidden: ({ document }) => document?.pageKey !== "home",
      initialValue: "Stichting Lumina · Tilburg",
    }),
    defineField({
      name: "heroPrimary",
      title: "Primaire knop in de hero",
      type: "object",
      group: "home",
      hidden: ({ document }) => document?.pageKey !== "home",
      fields: [defineField({ name: "label", title: "Tekst", type: "string" }), defineField({ name: "href", title: "Link", type: "string" })],
    }),
    defineField({
      name: "heroSecondary",
      title: "Secundaire link in de hero",
      type: "object",
      group: "home",
      hidden: ({ document }) => document?.pageKey !== "home",
      fields: [defineField({ name: "label", title: "Tekst", type: "string" }), defineField({ name: "href", title: "Link", type: "string" })],
    }),
    defineField({ name: "heroBadge", title: "Tekst in het ronde label", type: "string", group: "home", hidden: ({ document }) => document?.pageKey !== "home" }),
    defineField({ name: "heroCaption", title: "Bijschrift op de foto", type: "string", group: "home", hidden: ({ document }) => document?.pageKey !== "home" }),
    defineField({
      name: "heroTicker",
      title: "Woorden in de balk onder de hero",
      type: "array",
      group: "home",
      hidden: ({ document }) => document?.pageKey !== "home",
      of: [{ type: "string" }],
      validation: (Rule) => Rule.max(8),
    }),
    defineField({
      name: "homeSections",
      title: "Secties op de homepage",
      type: "array",
      group: "home",
      hidden: ({ document }) => document?.pageKey !== "home",
      description: "Voeg secties toe, verwijder ze of sleep ze in een andere volgorde.",
      of: [
        { type: "homeManifesto" },
        { type: "homePrograms" },
        { type: "homeEvent" },
        { type: "homeGallery" },
        { type: "homeTestimonial" },
        { type: "homePartners" },
        { type: "homeCta" },
      ],
    }),
    defineField({
      name: "seoTitle",
      title: "SEO başlığı",
      type: "string",
      group: "seo",
      description: "Boş bırakılırsa normal sayfa başlığı kullanılır.",
      validation: (Rule) => Rule.max(70).error("En fazla 70 karakter kullanın."),
    }),
    defineField({
      name: "metaDescription",
      title: "Meta açıklaması",
      type: "text",
      rows: 2,
      group: "seo",
      description: "Google ve sosyal medya önizlemeleri için kısa açıklama.",
      validation: (Rule) => Rule.max(160).error("En fazla 160 karakter kullanın."),
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "slug.current", media: "heroImage" },
  },
});
